spring.application.name=roomreserve

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/room_reserve
spring.datasource.username=krishnaamuluru
spring.datasource.password=${DB_PASSWORD}